<?php

namespace CodePress\CodeDatabase\Tests;

use CodePress\CodeDatabase\Contracts\CriteriaInterface;
use CodePress\CodeDatabase\Criteria\FindByNameAndDescription;
use CodePress\CodeDatabase\Repository\CategoryRepository;
use CodePress\CodeDatabase\Models\Category;
use Illuminate\Database\Query\Builder;

class FindByNameAndDescriptionTest extends AbstractTestCase
{

    /**
     * @var \CodePress\CodeDatabase\Repository\CategoryRepository
     */
    private $repository;

    /**
     * @var  FindByNameAndDescription
     */
    private $criteria;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->migrate();

        $this->repository = new CategoryRepository();
        $this->criteria = new FindByNameAndDescription('Category 1', 'desc 1');
        $this->createCategories();
    }

    public function test_if_instanceof_criteria_interface()
    {
        $this->assertInstanceOf(CriteriaInterface::class, $this->criteria);
    }

    /*public function test_if_apply_returns_query_builder()
    {
        $class = $this->repository->model();
        $result = $this->criteria->apply(new $class, $this->repository);
        $this->assertInstanceOf(Builder::class, $result);
    }*/

    public function test_if_apply_returns_data()
    {
        $class = $this->repository->model();
        $result = $this->criteria->apply(new $class, $this->repository)->get();
        $this->assertEquals('Category 1', $result->first()->name);
        $this->assertEquals('desc 1', $result->first()->description);
    }

    private function createCategories()
    {
        Category::create([
            'name' => 'Category 1',
            'description' => 'desc 1'
        ]);
        Category::create([
            'name' => 'Category 2',
            'description' => 'desc 2'
        ]);
        Category::create([
            'name' => 'Category 3',
            'description' => 'desc 3'
        ]);
    }

}